-- ____________________JOIN_________________
-- Operações de rota de cada companhia
-- Portões ocupados por operações de solo
-- Funcionários de cada operação de rota, com nome e setor
-- Operações de solo por companhia
-- Terceiros, companhia e solicitações
-- Solicitações por aeronave e funcionário responsável
-- Aeronaves sem nenhuma operação de rota
-- Pistas com designação, categoria ICAO e localização
-- Solicitações abertas por cada setor
-- Sequência de operações de solo encadeadas